name: Main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Załadowanie kodu
      uses: actions/checkout@v3
    - name: Podłączenie Node.js
      uses: actions/setup-node@v3
      with: 
        node-version: "16.x"
    - name: Instalacja dependencji
      run: npm install
    - name: Uruchomienie testów
      run: npm run test
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Załadowanie kodu
      uses: actions/checkout@v3
    - name: Podłączenie App Service
      uses: azure/appservice-build@v3
      with: 
        platform: nodejs
        version: 16.16.0
    - name: Wdrożenie aplikacji do Azure App Service
      uses: azure/webapps-deploy@v1
      with: 
        app-name: app3nodejs1
        publish-profile: ${{secrets.AZURE}}
        
      
    





      
